### PR TITLE
Add static tags

### PR DESCRIPTION
**Pull request by HerrDerb**
Closes: https://github.com/quarkiverse/quarkus-logging-sentry/issues/219

### CODE REVIEW

**Comment by HerrDerb** [comment]
@ia3andy bump 🙂

**Review by ia3andy — APPROVED** [review]
Thanks!!!

**Comment by ia3andy** [comment]
Sorry for the delay, so much notifs 😅

**Comment by melloware** [comment]
@all-contributors add @HerrDerb for code

**Pull request merged**
